// <auto-generated />
using System;
using GeneFlow.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeneFlow.Infrastructure.Data.Migrations
{
    [DbContext(typeof(GeneFlowDbContext))]
    [Migration("20260607044633_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GeneFlow.Core.Entities.AnalysisResult", b =>
                {
                    b.Property<Guid>("AnalysisResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("AnalysisRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<decimal?>("DeltaCt")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal?>("DeltaDeltaCt")
                        .HasColumnType("decimal(10,4)");

                    b.Property<Guid>("ExperimentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("FoldChange")
                        .HasColumnType("decimal(18,8)");

                    b.Property<bool>("HasWarning")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Log2FoldChange")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal?>("MeanReferenceCt")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal?>("MeanTargetCt")
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("ReferenceGene")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ReferenceReplicateCount")
                        .HasColumnType("int");

                    b.Property<string>("SampleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SampleType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("SdReferenceCt")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal?>("SdTargetCt")
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("TargetGene")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TargetReplicateCount")
                        .HasColumnType("int");

                    b.HasKey("AnalysisResultId");

                    b.HasIndex("AnalysisRunId");

                    b.HasIndex("ExperimentId");

                    b.ToTable("AnalysisResults");
                });

            modelBuilder.Entity("GeneFlow.Core.Entities.AnalysisRun", b =>
                {
                    b.Property<Guid>("AnalysisRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("CalculationMethod")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("DeltaDeltaCt");

                    b.Property<string>("ControlSampleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExperimentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("HighCtThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,4)")
                        .HasDefaultValue(35m);

                    b.Property<string>("ReferenceGene")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("ReplicateSdThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,4)")
                        .HasDefaultValue(0.5m);

                    b.Property<string>("RunName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("AnalysisRunId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ExperimentId");

                    b.ToTable("AnalysisRuns");
                });

            modelBuilder.Entity("GeneFlow.Core.Entities.AnalysisWarning", b =>
                {
                    b.Property<Guid>("AnalysisWarningId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid?>("AnalysisResultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnalysisRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid?>("PlateWellId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WarningMessage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("WarningType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AnalysisWarningId");

                    b.HasIndex("AnalysisResultId");

                    b.HasIndex("AnalysisRunId");

                    b.ToTable("AnalysisWarnings");
                });

            modelBuilder.Entity("GeneFlow.Core.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("LabId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AuditLogId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("GeneFlow.Core.Entities.Experiment", b =>
                {
                    b.Property<Guid>("ExperimentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("ControlSampleName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateOnly>("ExperimentDate")
                        .HasColumnType("date");

                    b.Property<string>("ExperimentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Hypothesis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstrumentName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("LabId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LockedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Objective")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PlateType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("96-well");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferenceGene")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SampleSource")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TreatmentCondition")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ExperimentId");

                    b.HasIndex("LabId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Experiments");
                });

            modelBuilder.Entity("GeneFlow.Core.Entities.ExperimentNote", b =>
                {
                    b.Property<Guid>("ExperimentNoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("ExperimentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NoteText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoteType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ExperimentNoteId");

                    b.HasIndex("ExperimentId");

                    b.HasIndex("UserId");

                    b.ToTable("ExperimentNotes");
                });

            modelBuilder.Entity("GeneFlow.Core.Entities.ExportFile", b =>
                {
                    b.Property<Guid>("ExportFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid?>("AnalysisRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExperimentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExportType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("ExportFileId");

                    b.HasIndex("AnalysisRunId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ExperimentId");

                    b.ToTable("ExportFiles");
                });

            modelBuilder.Entity("GeneFlow.Core.Entities.Lab", b =>
                {
                    b.Property<Guid>("LabId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstitutionName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LabName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("LabId");

                    b.ToTable("Labs");
                });

            modelBuilder.Entity("GeneFlow.Core.Entities.LabUser", b =>
                {
                    b.Property<Guid>("LabUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("LabId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LabRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LabUserId");

                    b.HasIndex("UserId");

                    b.HasIndex("LabId", "UserId")
                        .IsUnique();

                    b.ToTable("LabUsers");
                });

            modelBuilder.Entity("GeneFlow.Core.Entities.PlateLayout", b =>
                {
                    b.Property<Guid>("PlateLayoutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("ColumnCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("ExperimentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PlateType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("96-well");

                    b.Property<int>("RowCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PlateLayoutId");

                    b.HasIndex("ExperimentId");

                    b.ToTable("PlateLayouts");
                });

            modelBuilder.Entity("GeneFlow.Core.Entities.PlateWell", b =>
                {
                    b.Property<Guid>("PlateWellId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("ColumnNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<decimal?>("CtValue")
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("ExclusionReason")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("ExperimentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsExcluded")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PlateLayoutId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferenceGene")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReplicateGroup")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RowLabel")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("SampleName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SampleType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TargetGene")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WellId")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("PlateWellId");

                    b.HasIndex("ExperimentId");

                    b.HasIndex("PlateLayoutId", "WellId")
                        .IsUnique();

                    b.ToTable("PlateWells");
                });

            modelBuilder.Entity("GeneFlow.Core.Entities.Project", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("LabId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ProjectId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("LabId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("GeneFlow.Core.Entities.ProjectUser", b =>
                {
                    b.Property<Guid>("ProjectUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProjectRole")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Member");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProjectUserId");

                    b.HasIndex("UserId");

                    b.HasIndex("ProjectId", "UserId")
                        .IsUnique();

                    b.ToTable("ProjectUsers");
                });

            modelBuilder.Entity("GeneFlow.Core.Entities.RawCtData", b =>
                {
                    b.Property<Guid>("RawCtDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<decimal?>("CtValue")
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("CtValueRaw")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ExperimentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<string>("SampleNameFromFile")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TargetGeneFromFile")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UploadedFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ValidationMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("WellId")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("RawCtDataId");

                    b.HasIndex("ExperimentId");

                    b.HasIndex("UploadedFileId");

                    b.ToTable("RawCtData");
                });

            modelBuilder.Entity("GeneFlow.Core.Entities.UploadedFile", b =>
                {
                    b.Property<Guid>("UploadedFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("ExperimentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("StoredFilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UploadedFileId");

                    b.HasIndex("ExperimentId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("UploadedFiles");
                });

            modelBuilder.Entity("GeneFlow.Core.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SystemRole")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("User");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GeneFlow.Core.Entities.AnalysisResult", b =>
                {
                    b.HasOne("GeneFlow.Core.Entities.AnalysisRun", "AnalysisRun")
                        .WithMany("AnalysisResults")
                        .HasForeignKey("AnalysisRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GeneFlow.Core.Entities.Experiment", "Experiment")
                        .WithMany()
                        .HasForeignKey("ExperimentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnalysisRun");

                    b.Navigation("Experiment");
                });

            modelBuilder.Entity("GeneFlow.Core.Entities.AnalysisRun", b =>
                {
                    b.HasOne("GeneFlow.Core.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GeneFlow.Core.Entities.Experiment", "Experiment")
                        .WithMany("AnalysisRuns")
                        .HasForeignKey("ExperimentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Experiment");
                });

            modelBuilder.Entity("GeneFlow.Core.Entities.AnalysisWarning", b =>
                {
                    b.HasOne("GeneFlow.Core.Entities.AnalysisResult", "AnalysisResult")
                        .WithMany("AnalysisWarnings")
                        .HasForeignKey("AnalysisResultId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GeneFlow.Core.Entities.AnalysisRun", "AnalysisRun")
                        .WithMany("AnalysisWarnings")
                        .HasForeignKey("AnalysisRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnalysisResult");

                    b.Navigation("AnalysisRun");
                });

            modelBuilder.Entity("GeneFlow.Core.Entities.Experiment", b =>
                {
                    b.HasOne("GeneFlow.Core.Entities.Lab", "Lab")
                        .WithMany("Experiments")
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GeneFlow.Core.Entities.User", "OwnerUser")
                        .WithMany("OwnedExperiments")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GeneFlow.Core.Entities.Project", "Project")
                        .WithMany("Experiments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Lab");

                    b.Navigation("OwnerUser");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("GeneFlow.Core.Entities.ExperimentNote", b =>
                {
                    b.HasOne("GeneFlow.Core.Entities.Experiment", "Experiment")
                        .WithMany("ExperimentNotes")
                        .HasForeignKey("ExperimentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GeneFlow.Core.Entities.User", "User")
                        .WithMany("Notes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Experiment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GeneFlow.Core.Entities.ExportFile", b =>
                {
                    b.HasOne("GeneFlow.Core.Entities.AnalysisRun", "AnalysisRun")
                        .WithMany()
                        .HasForeignKey("AnalysisRunId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GeneFlow.Core.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GeneFlow.Core.Entities.Experiment", "Experiment")
                        .WithMany()
                        .HasForeignKey("ExperimentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnalysisRun");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Experiment");
                });

            modelBuilder.Entity("GeneFlow.Core.Entities.LabUser", b =>
                {
                    b.HasOne("GeneFlow.Core.Entities.Lab", "Lab")
                        .WithMany("LabUsers")
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GeneFlow.Core.Entities.User", "User")
                        .WithMany("LabUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lab");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GeneFlow.Core.Entities.PlateLayout", b =>
                {
                    b.HasOne("GeneFlow.Core.Entities.Experiment", "Experiment")
                        .WithMany("PlateLayouts")
                        .HasForeignKey("ExperimentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Experiment");
                });

            modelBuilder.Entity("GeneFlow.Core.Entities.PlateWell", b =>
                {
                    b.HasOne("GeneFlow.Core.Entities.Experiment", "Experiment")
                        .WithMany("PlateWells")
                        .HasForeignKey("ExperimentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GeneFlow.Core.Entities.PlateLayout", "PlateLayout")
                        .WithMany("PlateWells")
                        .HasForeignKey("PlateLayoutId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Experiment");

                    b.Navigation("PlateLayout");
                });

            modelBuilder.Entity("GeneFlow.Core.Entities.Project", b =>
                {
                    b.HasOne("GeneFlow.Core.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GeneFlow.Core.Entities.Lab", "Lab")
                        .WithMany("Projects")
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Lab");
                });

            modelBuilder.Entity("GeneFlow.Core.Entities.ProjectUser", b =>
                {
                    b.HasOne("GeneFlow.Core.Entities.Project", "Project")
                        .WithMany("ProjectUsers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GeneFlow.Core.Entities.User", "User")
                        .WithMany("ProjectUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GeneFlow.Core.Entities.RawCtData", b =>
                {
                    b.HasOne("GeneFlow.Core.Entities.Experiment", "Experiment")
                        .WithMany()
                        .HasForeignKey("ExperimentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GeneFlow.Core.Entities.UploadedFile", "UploadedFile")
                        .WithMany("RawCtData")
                        .HasForeignKey("UploadedFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Experiment");

                    b.Navigation("UploadedFile");
                });

            modelBuilder.Entity("GeneFlow.Core.Entities.UploadedFile", b =>
                {
                    b.HasOne("GeneFlow.Core.Entities.Experiment", "Experiment")
                        .WithMany("UploadedFiles")
                        .HasForeignKey("ExperimentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GeneFlow.Core.Entities.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Experiment");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("GeneFlow.Core.Entities.AnalysisResult", b =>
                {
                    b.Navigation("AnalysisWarnings");
                });

            modelBuilder.Entity("GeneFlow.Core.Entities.AnalysisRun", b =>
                {
                    b.Navigation("AnalysisResults");

                    b.Navigation("AnalysisWarnings");
                });

            modelBuilder.Entity("GeneFlow.Core.Entities.Experiment", b =>
                {
                    b.Navigation("AnalysisRuns");

                    b.Navigation("ExperimentNotes");

                    b.Navigation("PlateLayouts");

                    b.Navigation("PlateWells");

                    b.Navigation("UploadedFiles");
                });

            modelBuilder.Entity("GeneFlow.Core.Entities.Lab", b =>
                {
                    b.Navigation("Experiments");

                    b.Navigation("LabUsers");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("GeneFlow.Core.Entities.PlateLayout", b =>
                {
                    b.Navigation("PlateWells");
                });

            modelBuilder.Entity("GeneFlow.Core.Entities.Project", b =>
                {
                    b.Navigation("Experiments");

                    b.Navigation("ProjectUsers");
                });

            modelBuilder.Entity("GeneFlow.Core.Entities.UploadedFile", b =>
                {
                    b.Navigation("RawCtData");
                });

            modelBuilder.Entity("GeneFlow.Core.Entities.User", b =>
                {
                    b.Navigation("LabUsers");

                    b.Navigation("Notes");

                    b.Navigation("OwnedExperiments");

                    b.Navigation("ProjectUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
